# ==========================================
# SIEM Collector Configuration File
# ==========================================

# IPC Socket (Επικοινωνία με Python Engine)
SOCKET_PATH=/tmp/siem_socket

# Αρχεία Καταγραφής (Log Files)
AUTH_LOG=/var/log/auth.log
IDS_LOG=/var/log/suricata/eve.json

# Ιστορικό Εντολών (Command History)
ROOT_HISTORY=/root/.bash_history
USER_HISTORY=/home/test/.bash_history